### ISSUE TITLE
Snap update to v1.3.1

### ISSUE THREAD

**Issue by tbille** [casperdcl/cli#3]
### Describe the feature or problem you’d like to solve

Hey I noticed that the snap wasn't up to date it would be great to rebuild and publish to the latest version.

### Proposed solution

To make sure the snap is always building the latest version of the snap. It can be setup to autobuild  using the  build integration with GitHub (see [here](https://snapcraft.io/about/publish))

### Additional context

To be transparent I maintain snapcraft.io (web part) and would be happy to  help updating the snap :smile:

**Comment by casperdcl** [comment]
ah it is actually up-to-date but the version number is wrong (`0.5.5-pre.1-1945-g222d29b` means 1945 commits ahead of `v0.5.5`, which means `v1.4.0`...). Fixed now.
