### ISSUE TITLE
Uninstalling this snap uninstalled dotnet

### ISSUE THREAD

**Issue by SRNissen** [casperdcl/cli#48]
### Describe the feature or problem you’d like to solve

Uninstalling this snap uninstalled dotnet

### Proposed solution

Don't do that

### Additional context

On archlinux, with gh installed through snap instead of pacman, the version was pretty far behind and I needed a newer feature.

After uninstalling through snap and installing through pacman, suddenly I no longer have dotnet installed.

**Comment by lengau** [comment]
How was `dotnet` installed on your machine before? Unless the snap is classic-confined (none of the `gh` snap packages are classic-confined), it doesn't have the ability to remove other packages from your system (and that would require explicitly doing that, which this snap doesn't).

**Comment by SRNissen** [comment]
Pretty manually, with a bunch of symlinks.

It's the weirdest issue I've ever seen and I have no idea how to repro, but it's the only change that happened between "dotnet works" and "dotnet doesn't work."

**Comment by lengau** [comment]
I honestly cannot see how the snap could do this. All that removing the snap does is unmount the directory at `/snap/gh/<revision#>` and delete any `gh` snaps in `/var/lib/snapd/snaps`. Maybe it delete `~/snap/gh` too?

I suppose if your dotnet install required something inside of `/snap/gh` or `~/snap/gh` it could break it, but that'd be entirely beyond the control of this snap either

**Comment by SRNissen** [comment]
I have no idea how it happened, and it might well be a waste of your time to pursue it. I'm just reporting it because it happened and it was really weird.
